apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw-stack.fullname" . }}
  labels:
    {{- include "openclaw-stack.labels" . | nindent 4 }}
type: Opaque
data: {}
stringData:
  {{- range $key, $value := .Values.openclaw.env }}
  {{- if or (contains "KEY" (upper $key)) (contains "SECRET" (upper $key)) (contains "TOKEN" (upper $key)) (contains "PASSWORD" (upper $key)) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
